### ISSUE TITLE
You forked 6 repo's

### ISSUE THREAD

**Issue by Glixh** [Jude-Gideon/Blooket#63]
Sorry, you sent me an issue accusing me of not making code? You forked 6 people's repos. Also, I would think that someone who is a "pro" coder should know how to type. Your words, not mine, "you didn;t make this". So stop bothering me and putting issues that I can't fix, AKA your opinion.
I sound hypocritical right now for putting an issue that's not an issue.
![Screenshot 2022-12-15 9 03 30 PM](https://user-images.githubusercontent.com/118942002/208013310-1e63fc04-bc33-4ae1-a53a-d218e5263f61.png)
![Screenshot 2022-12-15 9 03 27 PM](https://user-images.githubusercontent.com/118942002/208013312-6991c9f3-a141-4272-8f0a-d1f0bccae67f.png)
![Screenshot 2022-12-15 9 03 23 PM](https://user-images.githubusercontent.com/118942002/208013314-e8d80e82-5144-4319-9029-07b364250aaa.png)
![Screenshot 2022-12-15 9 03 13 PM](https://user-images.githubusercontent.com/118942002/208013315-79bb8581-b014-4dc3-b38e-6006c2e6e92d.png)
![Screenshot 2022-12-15 9 03 08 PM](https://user-images.githubusercontent.com/118942002/208013317-d5fe11b9-987a-45e3-8472-4d9659faa9e5.png)
![Screenshot 2022-12-15 9 02 59 PM](https://user-images.githubusercontent.com/118942002/208013318-4b059a4e-9db8-4865-b8ab-532b5b008937.png)

**Comment by Jude-Gideon** [comment]
Bro.. Forking repos is something actual coders do 💀 you are just showing your inability to code, I also find it funny how you stalked my profile to get a shit ton of screen shots of me forking repos. Aldo everyone makes spelling mistakes but you don't mistakenly copy code, you can look up your code and there are 38 other people with identical code which isn't a coincidence. Just admit you can't code, forking repos most of the time means you're contributing to them to, if you were a cider you would know that's how GitHub works, in order to learn to code you should make your own scripts and not copy and paste.

**Comment by Jude-Gideon** [comment]
Also, I'm not accusing you you just did steal code, and you took heavy inspiration from glixzzy's name, this isn't a big deal I was just calling you out for not making hacks at least credit who you got the hacks from it's not a huge deal. 🤷‍♂️

**Comment by Jude-Gideon** [comment]
And stop saying you copying code is a "opinion" 💀 just admit your fault, credit the creator, and move on.

**Comment by Jude-Gideon** [comment]
> be quitet you are a nnod by sammping people repl

nobody can under stand shit youre saying

**Comment by Glixh** [comment]
Wtf is prndndndndnnndd even saying
